### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CarlosMChica** [PaNaVTEC/Wizard#5]
`````` java
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(:1365)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(:1383)
       at android.support.v4.app.BackStackRecord.commitInternal(:636)
       at android.support.v4.app.BackStackRecord.commit(:615)
       at me.panavtec.wizard.Wizard.navigateNext(:78)
       at com.carlosdelachica.finger.ui.wizards.base.BaseWizardActivity.navigateToNextStep(:265)
       at com.carlosdelachica.finger.ui.wizards.create_gesture.CreateGestureWizardActivity.onNextButtonClicked(:110)
       at com.carlosdelachica.finger.ui.wizards.base.BaseWizardActivity.onNextButtonClicked(:243)
       at com.carlosdelachica.finger.ui.wizards.base.BaseWizardActivity$$ViewInjector$1.doClick$3c7ec8c3(:24)
       at butterknife.internal.DebouncingOnClickListener.onClick(:22)
       at android.view.View.performClick(View.java:4475)
       at android.view.View$PerformClick.run(View.java:18786)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5493)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
       at dalvik.system.NativeStart.main(NativeStart.java)```
``````

**Comment by PaNaVTEC** [comment]
Fixed, I just protected the methods to avoid this error. I close this issue if you have any more problems, re-open it with new log. Thanks.
